In [6]:
import pandas as pd
from pathlib import Path
import os

In [2]:
def merge_two_df(df1: pd.DataFrame, df2: pd.DataFrame, on: list, exclude_cols: list) -> pd.DataFrame:
    # Combining df with df_kpmm_4
    df = pd.merge(
        df1,
        df2,
        on=on,
        how='left',
        suffixes=("", "_df2")
    )

    # drop only the df2 versions of excluded columns
    drop_cols = [f"{c}_df2" for c in exclude_cols if f"{c}_df2" in df.columns]
    df = df.drop(columns=drop_cols, errors="ignore")

    return df

In [13]:
def import_rasio() -> pd.DataFrame:
    """
    Import all Rasio data into one dataframe
    """

    exclude_cols = [
        'posisi',
        'company_name',
        'kbmi_type',
        'year',
        'quarter',
        'year_quarter',
        'company_date',
    ]
    
    # Path to this file's folder ("data")
    # base_path = Path(__file__).parent
    base_path = os.getcwd()
    # os.path.join(base_path, "FS from OJK", "Rasio", bank)

    # Build absolute paths to the Excel files
    file1 = os.path.join(base_path,  "summarized rasio - KBMI 1.xlsx")
    file4 = os.path.join(base_path,  "summarized rasio - KBMI 4.xlsx")
    file_aset_4 = os.path.join(base_path,  "summarized fitur aset - KBMI 4.xlsx")
    file_liabilitas_4 = os.path.join(base_path,  "summarized fitur liabilitas - KBMI 4.xlsx")
    file_kpmm_4 = os.path.join(base_path,  "summarized fitur kpmm - KBMI 4.xlsx")
    file_kualitas_4 = os.path.join(base_path,  "summarized fitur Kualitas Aset - KBMI 4.xlsx")
    file_laba_rugi_4 = os.path.join(base_path,  "summarized fitur Laba Rugi - KBMI 4.xlsx")
    file_lcr_nsfr_4 = os.path.join(base_path,  "summarized fitur lcr nsfr - KBMI 4.xlsx")

    # Read all data files
    df_kbmi_1 = pd.read_excel(file1)
    df_kbmi_1 = df_kbmi_1.drop(columns=["sort_key"], errors="ignore")

    df_kbmi_4 = pd.read_excel(file4)

    df_aset_4 = pd.read_excel(file_aset_4)

    df_liabilitas_4 = pd.read_excel(file_liabilitas_4)

    df_kpmm_4 = pd.read_excel(file_kpmm_4)

    df_kualitas_4 = pd.read_excel(file_kualitas_4)

    df_laba_rugi_4 = pd.read_excel(file_laba_rugi_4)

    df_lcr_nsfr_4 = pd.read_excel(file_lcr_nsfr_4)

    # Combining df rasio KBMI 1 and KBMI 4
    df = pd.concat([df_kbmi_1, df_kbmi_4], axis=0, join="outer", ignore_index=True)

    # Combining df with df_aset_4
    df = merge_two_df(df, df_aset_4, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_liabilitas_4
    df = merge_two_df(df, df_liabilitas_4, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_kpmm_4
    df = merge_two_df(df, df_kpmm_4, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_kualitas_4
    df = merge_two_df(df, df_kualitas_4, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_laba_rugi_4
    df = merge_two_df(df, df_laba_rugi_4, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    # Combining df with df_laba_rugi_4
    df = merge_two_df(df, df_lcr_nsfr_4, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    return df

def import_fitur_rasio() -> list :
    fitur_rasio = [
        'aset_produktif_bermasalah_dan_aset_non_produktif_bermasalah_terhadap_total_aset_produktif_dan_aset_non_produktif',
        'cadangan_kerugian_penurunan_nilai_(ckpn)_aset_keuangan_terhadap_aset_produktif',
        'npl_gross',
        'npl_net',
        'return_on_asset',
        'return_on_equity',
        'net_interest_margin',
        'biaya_operasional_terhadap_pendapatan_operasional',
        'loan_to_deposit_ratio',
        'posisi_devisa_neto_(pdn)_secara_keseluruhan',

        # Fitur dari Aset
        'penempat_pada_bank_lain_per_total_aset',
        'tagihan_spot_derivatif_forward_per_total_aset',
        'surat_berharga_yang_dimiliki_per_total_aset',
        'reverse_repo_per_total_aset',
        'tagihan_akseptasi_per_total_aset',
        'kyd_dan_pembiayaan_syariah_per_total_aset',
        'ckpn_aset_keuangan_per_kyd_dan_pembiayaan_syariah',

        # Fitur dari Liabilitas
        'casa_ratio',
        'rim_ratio',

        # Fitur dari Modal
        'kpmm_per_car',
        'kpmm_cet1',
        'modal_terhadap_aset',
        'modal_terhadap_kredit_bersih',
        'other_comprehensive_income_to_equity',

        # Fitur dari Kualitas Aset
        'ckpn_per_kredit_restruk',
        'ckpn_stage_2_3_per_kredit_restruk',
        'kredit_bermasalah_dan_restruk_per_kredit_yang_diberikan',
        'kredit_restruk_per_modal_inti',
        'laba_per_kredit_bermasalah_non_restruk',
        'laba_per_kredit_restruk',

        # Fitur dari Laba Rugi
        # 'other_comprehensive_income',
        'kredit_restruk_per_pendapatan_bunga',

        # Fitur dari LCR dan NSFR
        'lcr',
        'nsfr',
    ]

    return(fitur_rasio)

def import_dictionary_rasio() -> dict :
    dict_rasio = {
        'aset_produktif_bermasalah_dan_aset_non_produktif_bermasalah_terhadap_total_aset_produktif_dan_aset_non_produktif': 'Aset Bermasalah per Total Aset',
        'cadangan_kerugian_penurunan_nilai_(ckpn)_aset_keuangan_terhadap_aset_produktif': 'CKPN per Aset Prod',
        'npl_gross': 'NPL Gross',
        'npl_net': 'NPL Net',
        'return_on_asset': 'ROA',
        'return_on_equity': 'ROE',
        'net_interest_margin': 'NIM',
        'biaya_operasional_terhadap_pendapatan_operasional': 'BOPO',
        'loan_to_deposit_ratio': 'LDR',
        'posisi_devisa_neto_(pdn)_secara_keseluruhan': 'PDN',

        # Fitur dari Aset
        'penempat_pada_bank_lain_per_total_aset' : 'Penempatan pada Bank Lain per Total Aset',
        'tagihan_spot_derivatif_forward_per_total_aset' : 'Tagihan Spot Derivatif Forward per Total Aset',
        'surat_berharga_yang_dimiliki_per_total_aset' : 'Surat Berharga yang Dimiliki per Total Aset',
        'reverse_repo_per_total_aset' : 'Reverse Repo per Total Aset',
        'tagihan_akseptasi_per_total_aset' : 'Tagihan Akseptasi per Total Aset',
        'kyd_dan_pembiayaan_syariah_per_total_aset' : 'KYD dan Pembiayaan Syariah per Total Aset',
        'ckpn_aset_keuangan_per_kyd_dan_pembiayaan_syariah' : 'CKPN Aset Keuangan per KYD dan Pembiayaan Syariah',

        # Fitur dari Liabilitas
        'casa_ratio' : 'CASA Ratio',
        'rim_ratio' : 'RIM Ratio',

        # Fitur dari Modal
        'kpmm_per_car' : 'KPMM per CAR',
        'kpmm_cet1' : 'KPMM CET-1',
        'modal_terhadap_aset' : 'Modal terhadap Aset',
        'modal_terhadap_kredit_bersih' : 'Modal terhadap Kredit Bersih',
        'other_comprehensive_income_to_equity' : 'Other Comprehensive Income',

        # Fitur dari Kualitas Aset
        'ckpn_per_kredit_restruk' : 'Total CKPN per Kredit Restruk',
        'ckpn_stage_2_3_per_kredit_restruk' : 'CKPN Stage 2 & 3 per Kredit Restruk',
        'kredit_bermasalah_dan_restruk_per_kredit_yang_diberikan' : 'Kredit yang Restruk + Kredit Bermasalah non Restruk per Kredit yang Diberikan',
        'kredit_restruk_per_modal_inti' : 'Kredit yang Restruk per Modal Inti',
        'laba_per_kredit_bermasalah_non_restruk' : 'Laba per Kredit Bermasalah non Restruk',
        'laba_per_kredit_restruk' : 'Laba per Kredit Restruk',

        # Fitur dari Laba Rugi
        # 'other_comprehensive_income' : 'Other Comprehensive Income',
        'kredit_restruk_per_pendapatan_bunga' : 'Kredit Restruk per Pendapatan Bunga',

        # Fitur dari LCR dan NSFR
        'lcr' : 'LCR',
        'nsfr' : 'NSFR',
    }

    return(dict_rasio)

In [14]:
def import_numerik() -> pd.DataFrame:
    """
    Import all Rasio data into one dataframe
    """

    exclude_cols = [
        'posisi',
        'company_name',
        'kbmi_type',
        'year',
        'quarter',
        'year_quarter',
        'company_date',
    ]
    
    # Path to this file's folder ("data")
    # base_path = Path(__file__).parent
    base_path = os.getcwd()
    # os.path.join(base_path, "FS from OJK", "Rasio", bank)

    # Build absolute paths to the Excel files
    file4 = os.path.join(base_path, "summarized fitur Numeric - KBMI 4.xlsx")
    # file_aset_4 = base_path / "summarized fitur aset - KBMI 4.xlsx"

    # Read all data files
    df_kbmi_4 = pd.read_excel(file4)

    # df_aset_4 = pd.read_excel(file_aset_4)

    # Combining df rasio KBMI 1 and KBMI 4
    df = df_kbmi_4.copy()

    # # Combining df with df_aset_4
    # df = merge_two_df(df, df_aset_4, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

    return df

def import_fitur_numerik() -> list :
    fitur_numerik = [
        'total_ckpn_stage_2_dan_3',
        'total_npl_dan_restruk_npl',
    ]

    return(fitur_numerik)

def import_dictionary_numerik() -> dict :
    dict_numerik = {
        'total_ckpn_stage_2_dan_3': 'CKPN Stage 2 dan 3',
        'total_npl_dan_restruk_npl': 'Total NPL dan Restruk NPL',
    }

    return(dict_numerik)

In [19]:
exclude_cols = [
    'posisi',
    'company_name',
    'kbmi_type',
    'year',
    'quarter',
    'year_quarter',
    'company_date',
]

In [20]:
df_rasio = import_rasio()
fi_rasio = import_fitur_rasio()
column_rasio = exclude_cols + fi_rasio
dict_rasio = import_dictionary_rasio()

In [21]:
cleaned_rasio = df_rasio[column_rasio].rename(columns=dict_rasio)

In [22]:
cleaned_rasio

,posisi,company_name,kbmi_type,year,quarter,year_quarter,company_date,Aset Bermasalah per Total Aset,CKPN per Aset Prod,NPL Gross,...,Other Comprehensive Income,Total CKPN per Kredit Restruk,CKPN Stage 2 & 3 per Kredit Restruk,Kredit yang Restruk + Kredit Bermasalah non Restruk per Kredit yang Diberikan,Kredit yang Restruk per Modal Inti,Laba per Kredit Bermasalah non Restruk,Laba per Kredit Restruk,Kredit Restruk per Pendapatan Bunga,LCR,NSFR
0,2022-03-31,BCA Digital,KBMI 1,2022,q1,2022_q1,BCA Digital_2022q1,0.0068,0.0018,0.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-06-30,BCA Digital,KBMI 1,2022,q2,2022_q2,BCA Digital_2022q2,0.0053,0.0040,0.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-09-30,BCA Digital,KBMI 1,2022,q3,2022_q3,BCA Digital_2022q3,0.0042,0.0027,0.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-12-31,BCA Digital,KBMI 1,2022,q4,2022_q4,BCA Digital_2022q4,0.0041,0.0056,0.0009,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-03-31,BCA Digital,KBMI 1,2023,q1,2023_q1,BCA Digital_2023q1,0.0044,0.0059,0.0027,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,2024-09-30,"PT BANK RAKYAT INDONESIA (PERSERO), Tbk",KBMI 4,2024,q3,2024_q3,"PT BANK RAKYAT INDONESIA (PERSERO), Tbk_2024q3",0.0204,0.0480,0.0304,...,0.064783,0.859958,0.643130,0.090908,0.357718,1.948268,0.467234,0.733609,1.5497,1.2574
132,2024-12-31,"PT BANK CENTRAL ASIA, Tbk",KBMI 4,2024,q4,2024_q4,"PT BANK CENTRAL ASIA, Tbk_2024q4",0.0101,0.0253,0.0178,...,0.044652,1.157092,0.743129,0.038279,0.120210,10.001955,1.900411,0.324789,3.2301,1.5585
133,2024-12-31,PT BANK MANDIRI (PERSERO),KBMI 4,2024,q4,2024_q4,PT BANK MANDIRI (PERSERO)_2024q4,0.0068,0.0232,0.0097,...,0.134434,0.540431,0.425768,0.060405,0.319512,8.953204,0.696046,0.654165,1.3921,1.0760
134,2024-12-31,"PT BANK NEGARA INDONESIA (PERSERO), Tbk",KBMI 4,2024,q4,2024_q4,"PT BANK NEGARA INDONESIA (PERSERO), Tbk_2024q4",0.0149,0.0393,0.0197,...,0.105291,0.593649,0.542880,0.097948,0.502727,2.638120,0.318633,1.025119,1.4795,1.3248
135,2024-12-31,"PT BANK RAKYAT INDONESIA (PERSERO), Tbk",KBMI 4,2024,q4,2024_q4,"PT BANK RAKYAT INDONESIA (PERSERO), Tbk_2024q4",0.0191,0.0448,0.0294,...,0.066292,0.859095,0.660412,0.086058,0.350654,2.726905,0.648837,0.521007,1.5932,1.2777

In [23]:
df_numerik = import_numerik()
fi_numerik = import_fitur_numerik()
column_numerik = exclude_cols + fi_numerik
dict_numerik = import_dictionary_numerik()

In [24]:
cleaned_numerik = df_numerik[column_numerik].rename(columns=dict_numerik)

In [25]:
cleaned_numerik

,posisi,company_name,kbmi_type,year,quarter,year_quarter,company_date,CKPN Stage 2 dan 3,Total NPL dan Restruk NPL
0,2019-09-30,"PT BANK CENTRAL ASIA, Tbk",KBMI 4,2019,q3,2019_q3,"PT BANK CENTRAL ASIA, Tbk_2019q3",0,9246283
1,2019-09-30,PT BANK MANDIRI (PERSERO),KBMI 4,2019,q3,2019_q3,PT BANK MANDIRI (PERSERO)_2019q3,0,18974721
2,2019-09-30,"PT BANK NEGARA INDONESIA (PERSERO), Tbk",KBMI 4,2019,q3,2019_q3,"PT BANK NEGARA INDONESIA (PERSERO), Tbk_2019q3",0,9468447
3,2019-09-30,"PT BANK RAKYAT INDONESIA (PERSERO), Tbk",KBMI 4,2019,q3,2019_q3,"PT BANK RAKYAT INDONESIA (PERSERO), Tbk_2019q3",0,25183949
4,2019-12-31,"PT BANK CENTRAL ASIA, Tbk",KBMI 4,2019,q4,2019_q4,"PT BANK CENTRAL ASIA, Tbk_2019q4",0,7876926
...,...,...,...,...,...,...,...,...,...
83,2024-09-30,"PT BANK RAKYAT INDONESIA (PERSERO), Tbk",KBMI 4,2024,q3,2024_q3,"PT BANK RAKYAT INDONESIA (PERSERO), Tbk_2024q3",57361507,36982789
84,2024-12-31,"PT BANK CENTRAL ASIA, Tbk",KBMI 4,2024,q4,2024_q4,"PT BANK CENTRAL ASIA, Tbk_2024q4",21392161,15498016
85,2024-12-31,PT BANK MANDIRI (PERSERO),KBMI 4,2024,q4,2024_q4,PT BANK MANDIRI (PERSERO)_2024q4,31279591,12609239
86,2024-12-31,"PT BANK NEGARA INDONESIA (PERSERO), Tbk",KBMI 4,2024,q4,2024_q4,"PT BANK NEGARA INDONESIA (PERSERO), Tbk_2024q4",36130823,14985219
87,2024-12-31,"PT BANK RAKYAT INDONESIA (PERSERO), Tbk",KBMI 4,2024,q4,2024_q4,"PT BANK RAKYAT INDONESIA (PERSERO), Tbk_2024q4",55819794,35681873

In [26]:
cleaned_data = merge_two_df(cleaned_rasio, cleaned_numerik, on=['posisi', 'company_name'], exclude_cols=exclude_cols)

In [28]:
cleaned_data.to_excel("cleaned_all_data.xlsx", index=False)